FROM node:24-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY turbo.json ./

COPY ./packages ./packages
COPY ./apps/ws-backend ./apps/ws-backend

RUN pnpm install --frozen-lockfile

EXPOSE 3002

CMD ["pnpm", "run", "dev", "--filter=ws-backend"]