FROM node:24-alpine AS base

RUN corepack enable && corepack prepare pnpm@latest --activate

FROM base AS deps
WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY turbo.json ./

COPY packages/ ./packages/
COPY apps/ws-backend/ ./apps/ws-backend/

RUN pnpm install --shamefully-hoist

RUN cd packages/db && pnpm prisma generate

FROM base AS runner
WORKDIR /usr/src/app

COPY --from=deps /usr/src/app ./

EXPOSE 3002

CMD ["pnpm", "run", "dev", "--filter=ws-backend"]