FROM node:24-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY turbo.json ./

COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN pnpm install --frozen-lockfile

RUN pnpm run build --filter=web

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--filter=web"]